[platformio]
; Eger kodlarin Src ve Inc klasorlerinde kalmasini istiyorsaniz asagidaki satirlari kullanabilirsiniz
; eger VS Code + PlatformIO varsayilan (src, include) yapisini kullanacaksaniz ayarlari degistirin.
src_dir = Src
include_dir = Inc


[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube

; STM32Cube HAL framework'unde math kutyphanesini ve C99/C11 standartlarini aciyoruz
build_flags = 
    -I Inc
    -Wl,-u,_printf_float ; Eger snprintf ile float yazdiracaksaniz bu bayrak gereklidir
    -O2

; Eger CubeMX ile kod urettiyseniz ve "Core" klasorunde yer aliyorsa,
; src_dir = Core/Src
; include_dir = Core/Inc
; seklinde ayarlama yapabilirsiniz.

; --- Seri Port (Terminal) Ayarlari ---
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes
