set(__QT_DEPLOY_TARGET_Catch2_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/RelWithDebInfo/Catch2.lib)
set(__QT_DEPLOY_TARGET_Catch2_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_Catch2WithMain_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/RelWithDebInfo/Catch2Main.lib)
set(__QT_DEPLOY_TARGET_Catch2WithMain_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_tests_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/tests/RelWithDebInfo/preciscan_tests.exe)
set(__QT_DEPLOY_TARGET_preciscan_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_core_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/preciscan_core.lib)
set(__QT_DEPLOY_TARGET_preciscan_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_net_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/preciscan_net.lib)
set(__QT_DEPLOY_TARGET_preciscan_net_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_hw_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/preciscan_hw.lib)
set(__QT_DEPLOY_TARGET_preciscan_hw_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_acquire_cli_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/acquire_cli.exe)
set(__QT_DEPLOY_TARGET_acquire_cli_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_acquire_cli_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_udp_sender_sim_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/udp_sender_sim.exe)
set(__QT_DEPLOY_TARGET_udp_sender_sim_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_udp_sender_sim_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_trigger_test_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/trigger_test.exe)
set(__QT_DEPLOY_TARGET_trigger_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_trigger_test_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_ui_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/RelWithDebInfo/preciscan_ui.exe)
set(__QT_DEPLOY_TARGET_preciscan_ui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_ui_RUNTIME_DLLS C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGLWidgets.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Widgets.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGL.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Gui.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Core.dll)
