set(__QT_DEPLOY_TARGET_Catch2_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/MinSizeRel/Catch2.lib)
set(__QT_DEPLOY_TARGET_Catch2_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_Catch2WithMain_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/MinSizeRel/Catch2Main.lib)
set(__QT_DEPLOY_TARGET_Catch2WithMain_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_tests_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/tests/MinSizeRel/preciscan_tests.exe)
set(__QT_DEPLOY_TARGET_preciscan_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_core_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/preciscan_core.lib)
set(__QT_DEPLOY_TARGET_preciscan_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_net_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/preciscan_net.lib)
set(__QT_DEPLOY_TARGET_preciscan_net_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_hw_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/preciscan_hw.lib)
set(__QT_DEPLOY_TARGET_preciscan_hw_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_acquire_cli_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/acquire_cli.exe)
set(__QT_DEPLOY_TARGET_acquire_cli_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_acquire_cli_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_udp_sender_sim_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/udp_sender_sim.exe)
set(__QT_DEPLOY_TARGET_udp_sender_sim_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_udp_sender_sim_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_trigger_test_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/trigger_test.exe)
set(__QT_DEPLOY_TARGET_trigger_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_trigger_test_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_ui_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/MinSizeRel/preciscan_ui.exe)
set(__QT_DEPLOY_TARGET_preciscan_ui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_ui_RUNTIME_DLLS C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGLWidgets.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Concurrent.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_io.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_segmentation.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_search.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/flann_cpp.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Widgets.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGL.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Gui.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Core.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_io_ply.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_features.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_filters.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_sample_consensus.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_ml.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_kdtree.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_octree.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/lib/pcl_common.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_iostreams-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_random-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/zstd.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_filesystem-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_serialization-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_thread-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_atomic-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_chrono-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_date_time-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/boost_container-vc143-mt-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/bin/lz4.dll)
