set(__QT_DEPLOY_TARGET_Catch2_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/Debug/Catch2d.lib)
set(__QT_DEPLOY_TARGET_Catch2_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_Catch2WithMain_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/_deps/catch2-build/src/Debug/Catch2Maind.lib)
set(__QT_DEPLOY_TARGET_Catch2WithMain_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_tests_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/tests/Debug/preciscan_tests.exe)
set(__QT_DEPLOY_TARGET_preciscan_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_core_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/preciscan_core.lib)
set(__QT_DEPLOY_TARGET_preciscan_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_net_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/preciscan_net.lib)
set(__QT_DEPLOY_TARGET_preciscan_net_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_preciscan_hw_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/preciscan_hw.lib)
set(__QT_DEPLOY_TARGET_preciscan_hw_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_acquire_cli_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/acquire_cli.exe)
set(__QT_DEPLOY_TARGET_acquire_cli_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_acquire_cli_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_udp_sender_sim_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/udp_sender_sim.exe)
set(__QT_DEPLOY_TARGET_udp_sender_sim_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_udp_sender_sim_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_trigger_test_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/trigger_test.exe)
set(__QT_DEPLOY_TARGET_trigger_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_trigger_test_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_preciscan_ui_FILE C:/Users/Emirhan/OneDrive - Yildiz Technical University/Masaüstü/m2lab proje/Preciscan/pc/build_release/Debug/preciscan_ui.exe)
set(__QT_DEPLOY_TARGET_preciscan_ui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_preciscan_ui_RUNTIME_DLLS C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGLWidgetsd.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Concurrentd.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_iod.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_segmentationd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_searchd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/flann_cppd.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Widgetsd.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6OpenGLd.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Guid.dll;C:/Qt/6.10.1/msvc2022_64/bin/Qt6Cored.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_io_plyd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_featuresd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_filtersd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_sample_consensusd.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_mld.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_kdtreed.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_octreed.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/lib/pcl_commond.lib;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_iostreams-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_random-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/zstd.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_filesystem-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_serialization-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_thread-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_atomic-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_chrono-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_date_time-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/boost_container-vc143-mt-gd-x64-1_91.dll;C:/Users/Emirhan/vcpkg/installed/x64-windows/debug/bin/lz4d.dll)
